version = 0.1
[global]
[global.deploy]
[global.deploy.parameters]
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5yh6e98yptm4"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = false

[develop]
[develop.deploy]
[develop.deploy.parameters]
stack_name = "dropship-scraping-develop"
s3_prefix = "dropship-scraping-develop"
parameter_overrides=["stage=prod"]

[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "dropship-scraping"
s3_prefix = "dropship-scraping"
