version = 0.1
[develop]
[develop.deploy]
[develop.deploy.parameters]
stack_name = "dropship-scraping-develop"
s3_prefix = "dropship-scraping-develop"
parameter_overrides=["stage=prod"]
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5yh6e98yptm4"
region = "eu-central-1"
confirm_changeset = false
fail_on_empty_changeset=false
capabilities = "CAPABILITY_IAM"
image_repositories = []

[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "dropship-scraping"
s3_prefix = "dropship-scraping"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5yh6e98yptm4"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
