name: CD category predictor
on:
  push:
    branches: 
      - master
jobs:
  build:
    if: "startsWith(github.event.head_commit.message, 'build ami')"
    runs-on: ubuntu-latest
    steps:
      - name: pull from github
        run: echo "done"
